using Microsoft.EntityFrameworkCore;
using MvcBookshelf.Data;
using MvcBookshelf.Models;

namespace MvcBookshelf.Services
{
    public class BookshelfService : IBookshelfService
    {
        private readonly MvcBookshelfContext _db;

        public BookshelfService(MvcBookshelfContext db)
        {
            _db = db; // autogenerated constructor injection
        }

        public async Task<IEnumerable<Book>> GetAllAsync() => await _db.Book.ToListAsync();

        public async Task<Book?> GetByIdAsync(int id) =>
            await _db.Book.FirstOrDefaultAsync(b => b.ID == id);

        public async Task AddAsync(Book book)
        {
            _db.Book.Add(book);
            await _db.SaveChangesAsync();
        }


        public async Task UpdateAsync(Book book)
        {
            _db.Book.Update(book);
            await _db.SaveChangesAsync();
        }

        public async Task DeleteAsync(int id)
        {
            var entity = await _db.Book.FindAsync(id);
            if (entity is null) return;
            _db.Book.Remove(entity);
            await _db.SaveChangesAsync();
        }

        // implemented stats method logic into here
        public async Task<int> GetTotalBooksAsync()
        {
            return await _db.Book.CountAsync(); // copy over methods from BookController using db
        }

        public async Task<int> GetTotalAuthorsAsync()
        {
            return await _db.Book // get books to count distinct authors
                        .Select(book => book.Author) // select the author
                         // same tutorial section 2. Utilize Projection Queries to Fetch Only Required Columns
                        .Distinct() // ef core method for selecting distinct for no duplicates
                                    // https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable.distinct?view=net-9.0
                        .CountAsync(); // ef core async from section 1
        }

        public async Task<int> GetTotalGenresAsync()
        {
            return await _db.Book
                        .Select(book => book.Genre) // now get genre
                        .Distinct()
                        .CountAsync();
        }

        public async Task<int> GetTotalPagesAsync()
        {
            return await _db.Book // get books to sum pages
                        .Select(book => book.Pages) // select pages
                        .SumAsync(); // sum them

        }
    }
}
